// Regenerates src/default-cities.js from the all-the-cities package
// (GeoNames-derived). Run with: npm run generate:cities
//
// This bundles the FULL dataset (~130k cities worldwide, minus GeoNames'
// PPLX code for administrative sub-sections like boroughs/neighborhoods,
// which aren't really separate cities). That means importing this package
// adds several megabytes to a consumer's bundle — that's a deliberate
// trade-off for having every city available out of the box with no
// missing coverage. If you specifically want a smaller default, filter
// the `filtered` array below (e.g. by population) before writing it out,
// or just override the dataset at runtime via `picker.cities = [...]`
// with your own smaller/custom list instead of editing this script.
import cities from 'all-the-cities';
import { writeFileSync } from 'fs';

let filtered = cities.filter(c => c.featureCode !== 'PPLX'); // drop admin
                                                               // sub-sections
                                                               // (boroughs etc.)
filtered.sort((a, b) => b.population - a.population);

const seen = new Set();
const deduped = [];
for (const c of filtered) {
  const [lon, lat] = c.loc.coordinates;
  const key = `${c.name}|${c.country}|${lat.toFixed(3)}|${lon.toFixed(3)}`;
  if (seen.has(key)) continue;
  seen.add(key);
  deduped.push({
    name: c.name,
    country: c.country,
    lat: +lat.toFixed(4),
    lng: +lon.toFixed(4),
    population: c.population
  });
}

const out = `// Auto-generated by scripts/generate-cities.mjs — do not edit by hand.
export const DEFAULT_CITIES = ${JSON.stringify(deduped)};
`;
writeFileSync(new URL('../src/default-cities.js', import.meta.url), out);
console.log(`Wrote ${deduped.length} cities to src/default-cities.js`);
